name: MLflow CI - Text Emotion Classification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-mlflow-project:
    runs-on: ubuntu-latest

    steps:
    # Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # Setup Miniconda
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: MLProject/conda.yaml
        auto-activate-base: false

    # Debug: cek file & folder
    - name: List files
      run: ls -R

    # Aktifkan environment
    - name: Activate Conda environment
      run: conda activate text_emotion_env

    # Install MLflow (versi sesuai ketentuan)
    - name: Install MLflow
      run: pip install mlflow==2.19.0

    # Jalankan MLflow Project
    - name: Run MLflow Project
      run: |
        mlflow run MLProject \
          -P dataset_path=MLProject/text_emotion_preprocessing/text_emotion_clean.csv

    # Upload MLflow artifacts
    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlruns
        path: MLProject/mlruns
