name: MLflow CI - Text Emotion Classification

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-mlflow-project:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: https://dagshub.com/shofwatunisa/TextEmotion_Online.mlflow
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: MLProject/conda.yaml
          activate-environment: text_emotion_env
          auto-activate-base: false

      - name: Install MLflow & DagsHub
        run: |
          conda run -n text_emotion_env pip install mlflow dagshub

      - name: Run MLflow Project (CI Retraining)
        run: |
          conda run -n text_emotion_env mlflow run MLProject \
            -P dataset_path=MLProject/text_emotion_preprocessing/text_emotion_clean.csv \
            -P target_column=label
